name: tokosm_v2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  dotted_border: ^3.1.0
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_rating_bar: ^4.0.1
  geolocator: ^14.0.2
  http: ^1.4.0
  image_picker: ^1.2.0
  intl: ^0.20.0
  page_transition: ^2.2.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  solar_icons: ^0.0.5
  syncfusion_flutter_datepicker: ^30.1.42
  toastification: ^3.0.3
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo-tokosm.png"

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: fonts/Urbanist-Light.ttf
          weight: 300
        - asset: fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: fonts/Urbanist-Black.ttf
          weight: 900
        - asset: fonts/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Urbanist-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Urbanist-BlackItalic.ttf
          weight: 900
          style: italic
