name: tokosm_v2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_rating_bar: ^4.0.1
  http: ^1.4.0
  intl: ^0.20.2
  page_transition: ^2.2.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  solar_icons: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Italic-VariableFont_wght.ttf
        - asset: fonts/Urbanist-VariableFont_wght.ttf
          style: italic
